### ISSUE TITLE
option not to show filename

### ISSUE THREAD

**Issue by manogna4** [ravimashru/obsidian-show-file-path#1]
firstly, this is a useful little plugin! It was on my list of features I'd like to see in obsidian.

I suggest having an option not to show the filename in the statusbar. The filename is displayed on top of the note anyway, and can take a lot of space in the statusbar, especially if the filename is long.

**Comment by ravimashru** [comment]
That makes sense. :) I'll add a checkbox in the plugin options to show/hide the file name.

**Comment by ravimashru** [comment]
I just released version 0.1.0 that has a setting you can toggle to show the file name as a part of the path. Does that work for you?

**Comment by manogna4** [comment]
it works as expected. Another small suggestion though:

Currently it shows the path as `folder1/folder2`. It might be more appropriate to show it as `folder1/folder2/` just to emphasize that the last part is a folder and not a file name. idk what the standard is, but personally I prefer `/folder1/folder2/` to show that the path in relation to the root.

There are other extensions for special folder-notes, so the trailing slash will especially important in that context. I do not use them personally though.

**Comment by ravimashru** [comment]
That sounds interesting... what I plan to do in the (near) future is to do away with the `/` altogether and instead show something like the breadcrumb in file explorers (with a folder icon and `>` as a separator):
![image](https://user-images.githubusercontent.com/8961232/107735710-59efba80-6d26-11eb-8523-af31d01762a6.png)

IMO that should make files/folders more clear. I am also evaluating if it is possible to click a folder in that breadcrumb and have it expand in the Obsidian file explorer.

**Comment by manogna4** [comment]
I hope you make the icons an option. I wouldn't want to use them since they'll take up more space.
