### ISSUE TITLE
Could there be a screenshot in the docs?

### ISSUE THREAD

**Issue by claremacrae** [ravimashru/obsidian-show-file-path#10]
I've installed and enabled this on Mac, and restarted Obsidian, and I'm not spotting this!

I'm sure I'm missing something obvious... Would there be any chance of a screenshot being added to the README please, so users know what they will see when they have this set up?

**Comment by ravimashru** [comment]
I've wanted to add a screenshot for a long time but was just too lazy I guess. Thank you so much for taking the time to create a PR for this! 🙂
