### ISSUE TITLE
Feature: Highlight file on File Explorer

### ISSUE THREAD

**Issue by psarras** [ravimashru/obsidian-show-file-path#13]
Thanks for your plugin. I often use it to see exactly where the file is located but subsequently I want to move it. I know need to read the path, and try and un-collapse my folder accordingly. It would be great if I could right click (or use a shortcut) and have the current file shown on the file explorer!

**Comment by ravimashru** [comment]
Hey 👋

Thanks for using the plugin! I'm glad you find it useful. 🙂 

Obsidian has an option (under "More options") to "Reveal file in navigation" which, I believe, does what you want - highlights the currently open file in the file explorer.

![image](https://user-images.githubusercontent.com/8961232/137959120-f0f4c815-0d81-44a5-baa8-b13f02c7ce00.png)

Are you looking for something else?

**Comment by psarras** [comment]
Oops, still very much a Noob on obsidian! :) Thank you for that!

**Comment by ravimashru** [comment]
No problem at all! Glad to help you find the feature you wanted. :)

Also, if you like the plugin, please consider starring it ;)

**Comment by void32** [comment]
Hi, is it possible to make a shortcut for this?

**Comment by psarras** [comment]
@void32  Yes, but it has nothing to do with this plugin. You should use the regular hotkey section on Obsidian settings!
