### ISSUE TITLE
can file path show at title of obsidian?

### ISSUE THREAD

**Issue by hyaray** [ravimashru/obsidian-show-file-path#14]
can file path show at title of obsidian?
it make easier for scripts to get the file path.

**Comment by ravimashru** [comment]
Do you mean showing the complete path where the file name is displayed (similar to this: https://forum.obsidian.md/t/allow-show-folder-path-in-title/425)?

**Comment by luckman212** [comment]
Try this plugin:

https://github.com/jplattel/open-note-to-window-title

**Comment by hyaray** [comment]
> Try this plugin:
> 
> https://github.com/jplattel/open-note-to-window-title

Thanks, this is what I want!!
