### ISSUE TITLE
Unsure how to copy path to clipboard

### ISSUE THREAD

**Issue by ngirard** [ravimashru/obsidian-show-file-path#6]
Heya,

I was intrigued by the ability to copy path to clipboard introduced with the latest release, but couldn't figure out how to leverage it (using latest Obsidian version on Ubuntu 21.04).

Would you mind taking a screenshot and showing where to click ?

Cheers

**Comment by ravimashru** [comment]
Hello! 

Thanks for using the plugin! 

Just left-clicking on the path in the status bar should do the trick.

I'll record a GIF and post it here in a while :)

**Comment by ngirard** [comment]
@ravimashru, I'm not quite sure what happened, but the path didn't appear in the status bar, which lead me to file this issue.

After you made your comment I double-checked and there it was. Go figure...

I'm closing this issue. Sorry for the noise, but that said, adding a small gif to the README page wouldn't be useless IMHO.

Thanks for your efforts & assistance !
