### ISSUE TITLE
Ability to copy absolute path to clipboard

### ISSUE THREAD

**Issue by ngirard** [ravimashru/obsidian-show-file-path#7]
The latest release introduced the ability to copy the path to the clipboard.
Currently, the copied path is relative to the vault path.
It would be much useful to me, if I could get the absolute path instead.

Cheers

**Comment by ravimashru** [comment]
I just released version 0.4.0 of the plugin with this feature. You can go to settings and turn **Copy absolute path** on to copy the absolute path. Let me know if this works for you. :)
